### ISSUE TITLE
About "Right-click drag doesn't work in Dolphin."

### ISSUE THREAD

**Issue by Chuhtra** [glibg10b/ltt-linux-challenge-issues#4]
Right-clicking in Dolphin does work. What he tries to do is drag 'n drop with right click, from Dolphin to Desktop. This functionality is already there, all you have to do is use the LEFT mouse click.

**Comment by ansingh** [comment]
Just adding to this: windows on right-click allows you to see contextual options to cut / copy / create shortcut. That's also possible in dolphin.

You start a normal drag with left-click and instead of dropping it where you want, you right click on the target area and you'll be given those options to choose.
