### ISSUE TITLE
github pages broken

### ISSUE THREAD

**Issue by Samisafool** [glibg10b/ltt-linux-challenge-issues#5]

**Comment by fleshin** [comment]
Github pages are not broken. The GoXLR repo instructions asked the user to download the script and execute it, The script would then proceed to clone the repo. The problem was that in order to download the script, Linux decided to right click on the link and select "Save link as". The browser would then download the summary page for the file instead of the actual file. This is not a problem with github or even the browsers. You could say that the repo instructions were not specific enough. Shortly after the video the the goxlr instructions were updated/clarified asking to use wget of the raw file link. So, this could be considered fix IMO.

**Comment by Samisafool** [comment]
I'm not saying that, I'm talking about this: https://github.com/glibg10b/ltt-linux-challenge-issues/deployments/activity_log?environment=github-pages

The github pages site doesn't work

**Comment by glibg10b** [comment]
Thanks, deleting the branch didn't remove it so I had to remove it manually.
